-- K-Dictation : Stantalk 데이터베이스 스키마
-- 초기 마이그레이션 파일

-- ============================================
-- 1. Enum 타입 생성
-- ============================================

-- 구독 티어 (무료/프로)
CREATE TYPE subscription_tier AS ENUM ('free', 'pro');

-- 난이도 레벨
CREATE TYPE difficulty_level AS ENUM ('easy', 'normal', 'hard');

-- ============================================
-- 2. 테이블 생성
-- ============================================

-- 2.1 사용자 테이블
CREATE TABLE users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  avatar_url TEXT,
  subscription_tier subscription_tier DEFAULT 'free',
  streak_count INTEGER DEFAULT 0,
  last_study_date DATE,
  xp INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 리더보드용 인덱스
CREATE INDEX idx_users_xp ON users(xp DESC);

-- 2.2 콘텐츠(영상) 테이블
CREATE TABLE contents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  youtube_id TEXT NOT NULL, -- 예: "dQw4w9WgXcQ"
  title TEXT NOT NULL,
  artist_name TEXT NOT NULL, -- 예: "BTS", "NewJeans"
  thumbnail_url TEXT,
  difficulty difficulty_level DEFAULT 'normal',
  is_published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 아티스트 검색용 인덱스
CREATE INDEX idx_contents_artist ON contents(artist_name);

-- 2.3 챌린지(문제) 테이블
CREATE TABLE challenges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content_id UUID REFERENCES contents(id) ON DELETE CASCADE,
  start_sec FLOAT NOT NULL,
  end_sec FLOAT NOT NULL,
  full_sentence TEXT NOT NULL, -- 예: "밥 먹었어?"
  answer_word TEXT NOT NULL, -- 예: "먹었어"
  base_form TEXT, -- 예: "먹다" (단어장용)
  hint_en TEXT, -- 예: "Did you eat?"
  grammar_explanation TEXT, -- 예: "Past tense informal"
  order_index INTEGER DEFAULT 0, -- 문제 순서
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.4 사용자 진행상황 테이블
CREATE TABLE user_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  challenge_id UUID REFERENCES challenges(id),
  is_correct BOOLEAN DEFAULT FALSE,
  attempts INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.5 단어장 테이블
CREATE TABLE vocab_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  word TEXT NOT NULL,
  meaning TEXT NOT NULL,
  example_sentence TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, word) -- 중복 저장 방지
);

-- ============================================
-- 3. RLS (Row Level Security) 정책
-- ============================================

-- 사용자 테이블 RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile" ON users
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON users
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile" ON users
  FOR INSERT WITH CHECK (auth.uid() = id);

-- 콘텐츠 테이블 RLS (공개 읽기 가능)
ALTER TABLE contents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view published contents" ON contents
  FOR SELECT USING (is_published = TRUE);

-- 챌린지 테이블 RLS (공개 읽기 가능)
ALTER TABLE challenges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view challenges" ON challenges
  FOR SELECT USING (TRUE);

-- 사용자 진행상황 RLS
ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own progress" ON user_progress
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own progress" ON user_progress
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 단어장 RLS
ALTER TABLE vocab_book ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own vocab" ON vocab_book
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own vocab" ON vocab_book
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own vocab" ON vocab_book
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================
-- 4. 트리거 함수 (updated_at 자동 갱신)
-- ============================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
